### ISSUE TITLE
Cannot find module '@actions/core

### ISSUE THREAD

**Issue by srbarrios** [kunihiko-t/review-request-action#11]
Hi @kunihiko-t !

I'm trying to use your GitHub Action, but for some reason is failing and I'm not sure how to fix it.
That's my yml file:
```
name: add_pr_reviewer

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  qa_squad_review:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - uses: actions/setup-ruby@v1
    - name: "Check if there are test framework changes"
      run: |
        files_modified=`git diff --name-only "origin/$GITHUB_BASE_REF..HEAD" | xargs`
        ruby .github/scripts/needs_qa_squad_review.rb "$files_modified"
        
  add_pr_reviewer:
    needs: qa_squad_review
    runs-on: ubuntu-latest
    steps:
    - name: "Send Review Request to QA Squad"
      uses: kunihiko-t/review-request-action@master
      with:
        repo-token: ${{ secrets.TOKEN }}
        reviewers: "srbarrios,lkotek,Bischoff,ktsamis"
        team-reviewers: ""
```

This is the error happening when the second job starts (the one that trigger your GitHub Action) :

```2019-11-29T14:43:58.8596147Z ##[section]Starting: Request a runner to run this job
2019-11-29T14:43:59.0684194Z Requesting a hosted runner in current repository's account/organization with labels: 'ubuntu-latest', require runner match: True
2019-11-29T14:43:59.1134082Z Labels matched hosted runners has been found, waiting for one of them get assigned for this job.
2019-11-29T14:43:59.1445650Z ##[section]Finishing: Request a runner to run this job
2019-11-29T14:44:05.9017285Z Current runner version: '2.161.0'
2019-11-29T14:44:05.9018191Z Prepare workflow directory
2019-11-29T14:44:05.9209365Z Prepare all required actions
2019-11-29T14:44:05.9232597Z Download action repository 'kunihiko-t/review-request-action@master'
2019-11-29T14:44:08.3916147Z ##[group]Run kunihiko-t/review-request-action@master
2019-11-29T14:44:08.3916562Z with:
2019-11-29T14:44:08.3916784Z   reviewers: srbarrios,lkotek,Bischoff,ktsamis
2019-11-29T14:44:08.3916881Z ##[endgroup]
2019-11-29T14:44:08.7336707Z internal/modules/cjs/loader.js:626
2019-11-29T14:44:08.7337369Z     throw err;
2019-11-29T14:44:08.7337636Z     ^
2019-11-29T14:44:08.7337696Z 
2019-11-29T14:44:08.7338380Z Error: Cannot find module '@actions/core'
2019-11-29T14:44:08.7338525Z Require stack:
2019-11-29T14:44:08.7338924Z - /home/runner/work/_actions/kunihiko-t/review-request-action/master/lib/main.js
2019-11-29T14:44:08.7339101Z     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15)
2019-11-29T14:44:08.7339218Z     at Function.Module._load (internal/modules/cjs/loader.js:527:27)
2019-11-29T14:44:08.7342541Z     at Module.require (internal/modules/cjs/loader.js:681:19)
2019-11-29T14:44:08.7343299Z     at require (internal/modules/cjs/helpers.js:16:16)
2019-11-29T14:44:08.7344451Z     at Object.<anonymous> (/home/runner/work/_actions/kunihiko-t/review-request-action/master/lib/main.js:18:27)
2019-11-29T14:44:08.7345248Z     at Module._compile (internal/modules/cjs/loader.js:774:30)
2019-11-29T14:44:08.7345662Z     at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
2019-11-29T14:44:08.7346022Z     at Module.load (internal/modules/cjs/loader.js:641:32)
2019-11-29T14:44:08.7346399Z     at Function.Module._load (internal/modules/cjs/loader.js:556:12)
2019-11-29T14:44:08.7346795Z     at Function.Module.runMain (internal/modules/cjs/loader.js:837:10) {
2019-11-29T14:44:08.7347264Z   code: 'MODULE_NOT_FOUND',
2019-11-29T14:44:08.7347456Z   requireStack: [
2019-11-29T14:44:08.7348147Z     '/home/runner/work/_actions/kunihiko-t/review-request-action/master/lib/main.js'
2019-11-29T14:44:08.7348829Z   ]
2019-11-29T14:44:08.7349026Z }
2019-11-29T14:44:08.7359196Z ##[error]Node run failed with exit code 1
2019-11-29T14:44:08.7385512Z Cleaning up orphan processes```

Could you help me please? Thank you!
